name: CI
on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master, dev]
jobs:
  deploy-dbdocs:
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - run: yarn --frozen-lockfile
      - run: yarn prisma generate
      - run: env
      - run: ls -l node_modules/.bin
      - run: cat package.json
      - env:
          BRANCH: ${{ github.ref == 'refs/heads/master' && 'master' || 'dev' }}
          DBDOCS_TOKEN: ${{ secrets.DBDOCS_TOKEN }}
        run: yarn dbdocs build dbml/schema.dbml --project=${{ env.BRANCH }}

 
